# Puerto inválido:
  server {
    listen abc;
    server_name localhost;
}

# Token inesperado fuera de server:
  listen 8080;
server {
    server_name localhost;
}

# error_page sin ruta:
  server {
    listen 8080;
    error_page 404;
}

# client_max_body_size inválido:
  server {
    listen 8080;
    client_max_body_size abc;
}

# Directiva desconocida:
  server {
    listen 8080;
    pepito 123;
}

# return sin url:
  server {
    listen 8080;
    location /old {
        return 301;
    }
}

# server_name vacío:
  server {
    listen 8080;
    server_name ;
}