server {
    listen 8081;
    server_name localhost;

    location / {
        methods GET;
        root /home/mari-cruz/Escritorio/webserv/webserv/www;
        index index.html;
        autoindex off;
    }

    location /cgi-bin {
        methods POST;
        root /home/mari-cruz/Escritorio/webserv/webserv/www;
        cgi_pass .py /home/mari-cruz/Escritorio/webserv/webserv/www/cgi_tester;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100;
    }

    location /directory/ {
        methods GET;
        root /home/mnjie-me/mac/ebserv/webserver/www/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
    }
}