server {
    listen 8081;
    server_name localhost;

    client_max_body_size 1M;

    error_page 400 /home/mnjie-me/mac/webserv/webserv/errorPages/400.html;
    error_page 403 /home/mnjie-me/mac/webserv/webserv/errorPages/403.html;
    error_page 404 /home/mnjie-me/mac/webserv/webserv/errorPages/404.html;
    error_page 405 /home/mnjie-me/mac/webserv/webserv/errorPages/405.html;
    error_page 413 /home/mnjie-me/mac/webserv/webserv/errorPages/413.html;
    error_page 500 /home/mnjie-me/mac/webserv/webserv/errorPages/500.html;

    location / {
        root ./www;
        methods GET POST;
        index index.html;
        autoindex on;
        upload_store ./www/uploads;
    }

    location /readonly {
        root ./www;
        methods GET;
        autoindex off;
        index index.html;
    }

    location /files {
        root ./www;
        methods GET;
        autoindex on;
    }

    location /upload {
        root ./www/uploads;
        methods GET POST DELETE;
        upload_store ./www/uploads;
        client_max_body_size 10M;
        autoindex on;
    }

    location /post_body {
        root ./www;
        methods POST;
        client_max_body_size 100;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        methods GET POST;
        cgi_pass .py;
    }

    location /old-page {
        return 301 /new-page;
    }

    location /temp {
        return 302 /;
    }

    location /new-page {
        root ./www;
        methods GET;
        index index.html;
    }
    location /directory {
    root ./www;
    methods GET;
    index index.html;
    autoindex off;
    }
}

server {
    listen 8082;
    server_name test.localhost;

    client_max_body_size 500;

    location / {
        root ./www;
        methods GET;
        index index.html;
        autoindex off;
    }

    location /post-test {
        root ./www;
        methods POST;
        client_max_body_size 100;
    }
    location /cgi-bin {
        root ./www/cgi-bin;
        methods GET POST;
        cgi_pass .php;
    }
}
