server {
    listen 8080;
    server_name localhost;
    error_page 404 /Users/immaranieri/Desktop/Webserv/webserver entero/error pages404.html;
    error_page 500 /Users/immaranieri/Desktop/Webserv/webserver entero/error pages500.html;
    client_max_body_size 1M;

    location / {
        root /Users/immaranieri/Desktop/Webserv/webserver entero/www;
        methods GET POST;
        index index.html;
        autoindex off;
    }

    location /upload {
    root /Users/immaranieri/Desktop/Webserv/webserver entero/www/uploads;
    methods GET POST DELETE;
    upload_store /Users/immaranieri/Desktop/Webserv/webserver entero/www/uploads;
    autoindex on;
    }

    location /cgi-bin {
        root /Users/immaranieri/Desktop/Webserv/webserver entero/www/cgi-bin;
        methods GET POST;
        cgi_pass .php;
    }

    location /old-page {
        return 301 http://www.google.com;
    }

    location /files {
        root /Users/immaranieri/Desktop/Webserv/webserver entero/www/no_file;
        methods GET;
        autoindex off;
    }
}

server {
    listen 8090;
    server_name localhost;
    location / {
        root /Users/immaranieri/Desktop/Webserv/webserver entero/www;
        methods GET;
        index index.html;
        autoindex off;
    }
}