# location sin path:  
server {
    listen 8080;
    location {
        root /var/www;
    }
}

# location sin llaves:
  server {
    listen 8080;
    location / 
        root /var/www;
    }
}

# autoindex con valor inválido:
  server {
    listen 8080;
    location / {
        autoindex maybe;
    }
}

# return sin código:
  server {
    listen 8080;
    location /old {
        return ;
    }
}

# return con código inválido:
server {
    listen 8080;
    location /old {
        return abc /new;
    }
}

# error_page con código inválido:  
server {
    listen 8080;
    error_page abc /error.html;
}

# client_max_body_size negativo:  
server {
    listen 8080;
    client_max_body_size -1M;
}

# server vacío:
  server {
}

# archivo vacío:  

# sin llaves de cierre:
  server {
    listen 8080;
    server_name localhost;
  