server {
    listen 8080;
    server_name localhost;

    location / {
        methods GET;
        root /home/iranieri/Desktop/Webserv/webserver/www;
        index index.html;
        autoindex off;
    }

    location /cgi-bin {
        methods POST;
        root /home/iranieri/Desktop/Webserv/webserver/www;
        cgi_pass .bla /home/iranieri/Desktop/Webserv/webserver/cgi_tester;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100;
    }

    location /directory {
        methods GET;
        root /home/iranieri/Desktop/Webserv/webserver/www/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
    }
}